FROM node:22.16.0

WORKDIR /app

COPY package*.json ./
RUN npm install -g pnpm
RUN pnpm install

COPY . .

RUN pnpm prisma generate --schema ./prisma/schema.prisma

CMD ["pnpm", "run", "start:dev:docker"]
