FROM node:22.16.0

WORKDIR /app

COPY package*.json ./
RUN npm install

RUN npm install -g prisma ts-node-dev

COPY . .

RUN npx prisma generate --schema ./prisma/schema.prisma

CMD ["npm", "run", "start:dev:docker"]
